{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import time\n",
    "\n",
    "# pip/conda installed\n",
    "import dask.array as da\n",
    "import fsspec\n",
    "import pandas as pd\n",
    "import xarray as xr\n",
    "from dask.distributed import as_completed\n",
    "from dask.distributed import Client\n",
    "from dask_gateway import GatewayCluster\n",
    "\n",
    "from utils import get_logger\n",
    "from utils.dask import create_cluster\n",
    "from utils.dask import upload_source\n",
    "from utils.hls.catalog import HLSBand\n",
    "from utils.hls.catalog import HLSCatalog\n",
    "from utils.hls.catalog import scene_to_urls\n",
    "from utils.hls.compute import process_catalog\n",
    "from utils.hls.compute import calculate_job_median"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "logger = get_logger('hls-wa-test')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# fill with your account key\n",
    "os.environ['AZURE_ACCOUNT_KEY'] = \"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# read the entire data once (each tile is 3660x3660)...\n",
    "chunks = {'band': 1, 'x': 3660, 'y': 3660}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "catalog_url = fsspec.get_mapper(\n",
    "    f\"az://fia/catalogs/hls_wa_2015-2019.zarr\",\n",
    "    account_name=\"usfs\",\n",
    "    account_key=os.environ['AZURE_ACCOUNT_KEY']\n",
    ")\n",
    "catalog = HLSCatalog.from_zarr(catalog_url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cluster dashboard visible at: /services/dask-gateway/clusters/default.cbff43cbf5df421a9074d2144501651c/status\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "9b00a2d4e6ff49dc9ede25ae69c48549",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "VBox(children=(HTML(value='<h2>GatewayCluster</h2>'), HBox(children=(HTML(value='\\n<div>\\n<style scoped>\\n    â€¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "cluster = create_cluster(\n",
    "    workers=6,\n",
    "    worker_threads=1,\n",
    "    worker_memory=6,\n",
    "    scheduler_threads=4,\n",
    "    scheduler_memory=8\n",
    ")\n",
    "client = cluster.get_client()\n",
    "cluster"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# All workers must be started when source code is uploaded to them.\n",
    "upload_source('./', client)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "account_name=\"usfs\"\n",
    "storage_container=\"fia/hls-testing/wa\"\n",
    "account_key=os.environ[\"AZURE_ACCOUNT_KEY\"]\n",
    "catalog_groupby = \"tile\"\n",
    "job_groupby = \"time.month\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Filter to scenes from 2015 and later, then group by year\n",
    "yr_catalogs = catalog.xr_ds.where(catalog.xr_ds['year'] >= 2017, drop=True).groupby('year')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2021-01-07 23:42:50,942 [INFO] hls-wa-test - Starting process for 2017.0\n",
      "xarray.Dataset {\n",
      "dimensions:\n",
      "\tindex = 5041 ;\n",
      "\n",
      "variables:\n",
      "\tdatetime64[ns] dt(index) ;\n",
      "\tobject scene(index) ;\n",
      "\tobject sensor(index) ;\n",
      "\tobject tile(index) ;\n",
      "\tfloat64 year(index) ;\n",
      "\tint64 index(index) ;\n",
      "\n",
      "// global attributes:\n",
      "\t:bands = [<HLSBand.COASTAL_AEROSOL: 1>, <HLSBand.BLUE: 2>, <HLSBand.GREEN: 3>, <HLSBand.RED: 4>, <HLSBand.NIR_NARROW: 5>, <HLSBand.SWIR1: 6>, <HLSBand.SWIR2: 7>, <HLSBand.CIRRUS: 8>, <HLSBand.QA: 11>] ;\n",
      "}2021-01-07 23:42:52,165 [INFO] hls-wa-test - Submitting job 10TCT\n",
      "2021-01-07 23:43:05,903 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-kp85j1tv/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:43:05,904 [INFO] hls-wa-test - Submitting job 10TDR\n",
      "2021-01-07 23:43:26,607 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-vfl7hlko/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:43:26,608 [INFO] hls-wa-test - Submitting job 10TDS\n",
      "2021-01-07 23:44:01,336 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-y0ze4cqx/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:44:01,337 [INFO] hls-wa-test - Submitting job 10TDT\n",
      "2021-01-07 23:44:39,137 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-y0ze4cqx/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:44:39,138 [INFO] hls-wa-test - Submitting job 10TER\n",
      "2021-01-07 23:44:59,372 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-9w5_psia/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:44:59,373 [INFO] hls-wa-test - Submitting job 10TES\n",
      "2021-01-07 23:45:29,151 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-kp85j1tv/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:45:29,152 [INFO] hls-wa-test - Submitting job 10TET\n",
      "2021-01-07 23:45:56,370 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-y0ze4cqx/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:45:56,371 [INFO] hls-wa-test - Submitting job 10TFR\n",
      "2021-01-07 23:46:32,503 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-vfl7hlko/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:46:32,503 [INFO] hls-wa-test - Submitting job 10TFS\n",
      "2021-01-07 23:47:11,486 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-y0ze4cqx/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:47:11,487 [INFO] hls-wa-test - Submitting job 10TFT\n",
      "2021-01-07 23:47:51,337 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-9w5_psia/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:47:51,338 [INFO] hls-wa-test - Submitting job 10TGR\n",
      "2021-01-07 23:48:22,071 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-z_wnzfg6/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:48:22,072 [INFO] hls-wa-test - Submitting job 10TGS\n",
      "2021-01-07 23:48:55,557 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-y0ze4cqx/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:48:55,558 [INFO] hls-wa-test - Submitting job 10TGT\n",
      "2021-01-07 23:49:27,728 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-d_xc34mz/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:49:27,729 [INFO] hls-wa-test - Submitting job 10UCU\n",
      "2021-01-07 23:50:00,538 [ERROR] hls-wa-test - Exception from dask cluster\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/data-ingestion/utils/hls/compute.py\", line 243, in process_catalog\n",
      "    result = future.result()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"/home/jovyan/dask-worker-space/dask-worker-space/worker-y0ze4cqx/source.zip/utils/hls/compute.py\", line 122, in save_to_zarr\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py\", line 1745, in to_zarr\n",
      "    return to_zarr(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py\", line 1469, in to_zarr\n",
      "    zstore = backends.ZarrStore.open_group(\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py\", line 296, in open_group\n",
      "    zarr_group = zarr.open_group(store, **open_kwargs)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/hierarchy.py\", line 1181, in open_group\n",
      "    raise ContainsGroupError(path)\n",
      "zarr.errors.ContainsGroupError: path \"path '' contains a group\" contains a group\n",
      "2021-01-07 23:50:00,540 [INFO] hls-wa-test - Submitting job 10UCV\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-11-1899a1ab79fd>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      3\u001b[0m         \u001b[0mca\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minfo\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m         \u001b[0mstorage_prefix\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34mf\"{storage_container}/{yr}\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m         process_catalog(\n\u001b[0m\u001b[1;32m      6\u001b[0m             \u001b[0mcatalog\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mca\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m             \u001b[0mcatalog_groupby\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mcatalog_groupby\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/data-ingestion/utils/hls/compute.py\u001b[0m in \u001b[0;36mprocess_catalog\u001b[0;34m(catalog, catalog_groupby, job_fn, job_groupby, chunks, account_name, storage_container, account_key, client, concurrency, logger)\u001b[0m\n\u001b[1;32m    239\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    240\u001b[0m     \u001b[0mac\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mas_completed\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfirst_futures\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 241\u001b[0;31m     \u001b[0;32mfor\u001b[0m \u001b[0mfuture\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mac\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    242\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    243\u001b[0m             \u001b[0mresult\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfuture\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresult\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py\u001b[0m in \u001b[0;36m__next__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   4449\u001b[0m                 \u001b[0;32mraise\u001b[0m \u001b[0mStopIteration\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   4450\u001b[0m             \u001b[0;32mwith\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mthread_condition\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 4451\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mthread_condition\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0.100\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   4452\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_get_and_raise\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   4453\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/srv/conda/envs/notebook/lib/python3.8/threading.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    304\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    305\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0mtimeout\u001b[0m \u001b[0;34m>\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 306\u001b[0;31m                     \u001b[0mgotit\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mwaiter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0macquire\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    307\u001b[0m                 \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    308\u001b[0m                     \u001b[0mgotit\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mwaiter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0macquire\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "for yr, ca in yr_catalogs:\n",
    "        logger.info(f\"Starting process for {yr}\")\n",
    "        ca.info()\n",
    "        storage_prefix = f\"{storage_container}/{yr}\"\n",
    "        process_catalog(\n",
    "            catalog=ca,\n",
    "            catalog_groupby=catalog_groupby,\n",
    "            job_fn=calculate_job_median,\n",
    "            job_groupby=job_groupby,\n",
    "            chunks=chunks,\n",
    "            account_name=account_name,\n",
    "            storage_container=storage_prefix,\n",
    "            account_key=account_key,\n",
    "            client=client,\n",
    "            concurrency=1,\n",
    "            logger=logger\n",
    "        )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "cluster.shutdown()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:notebook] *",
   "language": "python",
   "name": "conda-env-notebook-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
